// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{chain}/{chain_id}/wallet/new": {
            "post": {
                "description": "Create \u0026 store a new wallet of the given chain and cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name",
                        "name": "chain",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain id",
                        "name": "chain_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wallet.NewWalletResponse"
                        }
                    }
                }
            }
        },
        "/{chain}/{chain_id}/{wallet}/execute": {
            "post": {
                "description": "Execute a payload with the given wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Execute a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target chain name",
                        "name": "chain",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target chain id",
                        "name": "chain_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target fund wallet address",
                        "name": "wallet",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wallet.ExecuteWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wallet.ExecuteWalletResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "wallet.ExecuteWalletRequest": {
            "type": "object",
            "properties": {
                "caller": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "wallet.ExecuteWalletResponse": {
            "type": "object",
            "properties": {
                "signatures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "wallet.NewWalletResponse": {
            "type": "object",
            "properties": {
                "wallet": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Signer API",
	Description:      "Avareum fund operation signing APIs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
